name: Deploy Django App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 3. Install dependencies
        run: pip install -r requirements.txt

      - name: 4. Cleaning testing files
        run: |
          rm -f db.sqlite3
          rm -f .env

      - name: 5. Zip artifact for deployment
        run: |
          zip -r release.zip . -x ".git/*" -x ".github/*"

      - name: 6. Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read 

    steps:
      - name: 1. Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: 2. Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'projetoreco'
          package: release.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}