# Generated by Django 5.2.1 on 2025-11-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Interesses',
            },
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='frequencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='interesses',
            field=models.ManyToManyField(blank=True, to='usuario.interesse'),
        ),
    ]
