# Generated by Django 5.2.1 on 2025-11-17 22:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_interesse_alter_perfil_options_perfil_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinanteNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inscrição Ativa')),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token para descadastro', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
            ],
            options={
                'verbose_name': 'Assinante da Newsletter',
                'verbose_name_plural': 'Assinantes da Newsletter',
                'ordering': ['-created_at'],
            },
        ),
    ]
