# Generated by Django 5.2.1 on 2025-12-09 01:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Manchete')),
                ('imagem_capa', models.ImageField(upload_to='edicoes/', verbose_name='Imagem da Capa')),
                ('link_leitura', models.URLField(verbose_name='Link para Leitura (PDF ou Site)')),
                ('data_publicacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Edição')),
            ],
            options={
                'verbose_name': 'Edição do Dia',
                'verbose_name_plural': 'Edições do Dia',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome (opcional)', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='E-mail (opcional)', max_length=254, null=True)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Enunciado da Pergunta')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('MUNDO', 'Mundo'), ('SEGURANCA_VIARIA', 'Segurança Viária'), ('CIDADES', 'Cidades'), ('POLITICA', 'Política'), ('GERAL', 'Geral'), ('EDUCACAO', 'Educação'), ('ESPORTE', 'Esporte'), ('SAUDE', 'Saúde e Bem-Estar'), ('MOBILIDADE', 'Mobilidade'), ('CULTURA', 'Cultura'), ('ENTRETENIMENTO', 'Entretenimento'), ('ECONOMIA', 'Economia'), ('COMERCIO', 'Comércio'), ('SOCIAL', 'Social')], default='GERAL', max_length=50, unique=True, verbose_name='Categoria')),
                ('imagem_banner', models.ImageField(blank=True, null=True, upload_to='banners_comunidade/')),
                ('imagem_card', models.ImageField(blank=True, null=True, upload_to='cards_comunidade/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunidades_criadas', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(blank=True, related_name='comunidades_seguidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunidade',
                'verbose_name_plural': 'Comunidades',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da notícia')),
                ('resumo', models.TextField(blank=True, help_text='Um breve resumo da notícia que aparecerá na home page.', null=True, verbose_name='Resumo (linha fina)')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da notícia')),
                ('categoria', models.CharField(choices=[('MUNDO', 'Mundo'), ('SEGURANCA_VIARIA', 'Segurança Viária'), ('CIDADES', 'Cidades'), ('POLITICA', 'Política'), ('GERAL', 'Geral'), ('EDUCACAO', 'Educação'), ('ESPORTE', 'Esporte'), ('SAUDE', 'Saúde e Bem-Estar'), ('MOBILIDADE', 'Mobilidade'), ('CULTURA', 'Cultura'), ('ENTRETENIMENTO', 'Entretenimento'), ('ECONOMIA', 'Economia'), ('COMERCIO', 'Comércio'), ('SOCIAL', 'Social')], default='GERAL', max_length=50, verbose_name='Categoria')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('slug', models.SlugField(blank=True, help_text='Usado para a URL da notícia. Deixe em branco para gerar automaticamente.', max_length=255, null=True, unique=True)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='noticias_imagens/', verbose_name='Imagem Principal')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto da Opção')),
                ('correta', models.BooleanField(default=False, verbose_name='É a resposta correta?')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='jornal_commercio.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('is_destaque', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to=settings.AUTH_USER_MODEL)),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='jornal_commercio.comunidade')),
                ('curtidas', models.ManyToManyField(blank=True, related_name='publicacoes_curtidas', to=settings.AUTH_USER_MODEL)),
                ('noticia_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes_comunidade', to='jornal_commercio.noticia', verbose_name='Notícia Relacionada')),
                ('salvo_por', models.ManyToManyField(blank=True, related_name='publicacoes_salvas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='jornal_commercio.publicacao')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título do Quiz')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/Instruções')),
                ('gerado_por_ia', models.BooleanField(default=False, verbose_name='Gerado automaticamente?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='jornal_commercio.noticia', verbose_name='Notícia Relacionada')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='jornal_commercio.quiz'),
        ),
        migrations.CreateModel(
            name='TentativaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('pontuacao', models.PositiveIntegerField(default=0, verbose_name='Acertos')),
                ('concluido', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='jornal_commercio.quiz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa de Quiz',
                'verbose_name_plural': 'Tentativas de Quiz',
                'unique_together': {('usuario', 'quiz')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem_lida', models.PositiveIntegerField(default=0, verbose_name='Porcentagem Lida')),
                ('lido_completo', models.BooleanField(default=False, verbose_name='Leitura Concluída')),
                ('ultima_interacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_leitura', to=settings.AUTH_USER_MODEL)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='jornal_commercio.noticia')),
            ],
            options={
                'verbose_name': 'Histórico de Leitura',
                'verbose_name_plural': 'Históricos de Leitura',
                'ordering': ['-ultima_interacao'],
                'unique_together': {('usuario', 'noticia')},
            },
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('opcao_escolhida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornal_commercio.opcao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornal_commercio.pergunta')),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='jornal_commercio.tentativaquiz')),
            ],
            options={
                'unique_together': {('tentativa', 'pergunta')},
            },
        ),
    ]
