# Generated by Django 5.2.1 on 2025-11-18 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_commercio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem_lida', models.PositiveIntegerField(default=0, verbose_name='Porcentagem Lida')),
                ('lido_completo', models.BooleanField(default=False, verbose_name='Leitura Concluída')),
                ('ultima_interacao', models.DateTimeField(auto_now=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='jornal_commercio.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_leitura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Leitura',
                'verbose_name_plural': 'Histórico de Leituras',
                'ordering': ['-ultima_interacao'],
                'unique_together': {('usuario', 'noticia')},
            },
        ),
    ]
