# Generated by Django 5.2.1 on 2025-12-10 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_commercio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome para identificação interna no admin.', max_length=150, verbose_name='Título Interno')),
                ('imagem', models.ImageField(upload_to='anuncios/', verbose_name='Banner/Imagem')),
                ('link_destino', models.URLField(help_text='Para onde o usuário será levado ao clicar.', verbose_name='Link de Destino')),
                ('posicao', models.CharField(choices=[('TOPO', 'Topo (Header)'), ('SIDEBAR', 'Barra Lateral (Sidebar)'), ('ENTRE_NOTICIAS', 'Entre Notícias (Feed)'), ('RODAPE', 'Rodapé'), ('MODAL', 'Pop-up/Modal')], default='SIDEBAR', max_length=30, verbose_name='Posição no Site')),
                ('categoria_alvo', models.CharField(blank=True, choices=[('MUNDO', 'Mundo'), ('SEGURANCA_VIARIA', 'Segurança Viária'), ('CIDADES', 'Cidades'), ('POLITICA', 'Política'), ('GERAL', 'Geral'), ('EDUCACAO', 'Educação'), ('ESPORTE', 'Esporte'), ('SAUDE', 'Saúde e Bem-Estar'), ('MOBILIDADE', 'Mobilidade'), ('CULTURA', 'Cultura'), ('ENTRETENIMENTO', 'Entretenimento'), ('ECONOMIA', 'Economia'), ('COMERCIO', 'Comércio'), ('SOCIAL', 'Social')], help_text='Se selecionado, o anúncio aparecerá apenas em páginas dessa categoria. Deixe em branco para aparecer em todo o site.', max_length=50, null=True, verbose_name='Categoria Alvo (Opcional)')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início da Veiculação')),
                ('data_fim', models.DateTimeField(blank=True, help_text='Deixe em branco para veicular indeterminadamente.', null=True, verbose_name='Fim da Veiculação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('visualizacoes', models.PositiveIntegerField(default=0, editable=False, verbose_name='Visualizações')),
                ('cliques', models.PositiveIntegerField(default=0, editable=False, verbose_name='Cliques')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['-ativo', '-data_inicio'],
            },
        ),
    ]
