# Generated by Django 5.2.1 on 2025-12-09 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_commercio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='descurtidas',
            field=models.ManyToManyField(blank=True, related_name='publicacoes_descurtidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
