# Generated by Django 5.2.1 on 2025-12-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_commercio', '0002_publicacao_descurtidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicao',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título Principal'),
        ),
    ]
