# Generated by Django 5.2.1 on 2025-11-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_commercio', '0002_historicoleitura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoleitura',
            options={'ordering': ['-ultima_interacao'], 'verbose_name': 'Histórico de Leitura', 'verbose_name_plural': 'Históricos de Leitura'},
        ),
    ]
