# Generated by Django 5.2.1 on 2025-12-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_commercio', '0002_anuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='link_destino',
            field=models.URLField(help_text="Para onde o usuário será levado ao clicar. Se não houver, coloque '#' ou deixe em branco.", verbose_name='Link de Destino'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='posicao',
            field=models.CharField(choices=[('TOPO', 'Topo (Header) - Global'), ('RODAPE', 'Rodapé - Global'), ('MODAL', 'Pop-up/Modal - Global'), ('HOME_MEIO_1', 'Home - Meio 1 (Abaixo dos Destaques)'), ('HOME_MEIO_2', 'Home - Meio 2 (Entre Comunidades e JC Quest)'), ('HOME_MEIO_3', 'Home - Meio 3 (Acima do Rodapé de Produtos)'), ('NOTICIA_TOPO', 'Notícia - Topo (Abaixo do Título)'), ('NOTICIA_MEIO_1', 'Notícia - Meio 1 (Após a Imagem Principal)'), ('NOTICIA_MEIO_2', 'Notícia - Meio 2 (Entre Parágrafos)'), ('NOTICIA_RODAPE', 'Notícia - Rodapé (Fim da Matéria)')], max_length=30, verbose_name='Posição no Site'),
        ),
    ]
