# Generated by Django 5.2.1 on 2025-11-24 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_commercio', '0003_alter_historicoleitura_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Enunciado da Pergunta')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto da Opção')),
                ('correta', models.BooleanField(default=False, verbose_name='É a resposta correta?')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='jornal_commercio.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título do Quiz')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/Instruções')),
                ('gerado_por_ia', models.BooleanField(default=False, verbose_name='Gerado automaticamente?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='jornal_commercio.noticia', verbose_name='Notícia Relacionada')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='jornal_commercio.quiz'),
        ),
        migrations.CreateModel(
            name='TentativaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('pontuacao', models.PositiveIntegerField(default=0, verbose_name='Acertos')),
                ('concluido', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='jornal_commercio.quiz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa de Quiz',
                'verbose_name_plural': 'Tentativas de Quiz',
                'unique_together': {('usuario', 'quiz')},
            },
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('opcao_escolhida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornal_commercio.opcao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornal_commercio.pergunta')),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='jornal_commercio.tentativaquiz')),
            ],
            options={
                'unique_together': {('tentativa', 'pergunta')},
            },
        ),
    ]
