# Generated by Django 5.2.1 on 2025-12-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_commercio', '0004_pergunta_opcao_quiz_pergunta_quiz_tentativaquiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidade',
            name='categoria',
            field=models.CharField(choices=[('MUNDO', 'Mundo'), ('SEGURANCA_VIARIA', 'Segurança Viária'), ('CIDADES', 'Cidades'), ('POLITICA', 'Política'), ('GERAL', 'Geral'), ('EDUCACAO', 'Educação'), ('ESPORTE', 'Esporte'), ('SAUDE', 'Saúde e Bem-Estar'), ('MOBILIDADE', 'Mobilidade'), ('CULTURA', 'Cultura'), ('ENTRETENIMENTO', 'Entretenimento'), ('ECONOMIA', 'Economia'), ('COMERCIO', 'Comércio'), ('SOCIAL', 'Social')], default='GERAL', max_length=50, unique=True, verbose_name='Categoria'),
        ),
    ]
