# Generated by Django 5.2.1 on 2025-12-01 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_commercio', '0005_alter_comunidade_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='noticia_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes_comunidade', to='jornal_commercio.noticia', verbose_name='Notícia Relacionada'),
        ),
    ]
