# Generated by Django 5.2.1 on 2025-12-08 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal_commercio', '0006_publicacao_noticia_relacionada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Manchete')),
                ('imagem_capa', models.ImageField(upload_to='edicoes/', verbose_name='Imagem da Capa')),
                ('link_leitura', models.URLField(verbose_name='Link para Leitura (PDF ou Site)')),
                ('data_publicacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Edição')),
            ],
            options={
                'verbose_name': 'Edição do Dia',
                'verbose_name_plural': 'Edições do Dia',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
